package devices

import algebra.DeviceDef
import algebra.Messages.ProgramChange

object Gervill extends DeviceDef("Gervill") {
  object AcousticGrandPiano extends ProgramChange(0)   // 0
  object BrightAcousticPian extends ProgramChange(1)   // 0
  object ElectricGrandPiano extends ProgramChange(2)   // 0
  object HonkyTonkPiano     extends ProgramChange(3)   // 0
  object ElectricPiano1     extends ProgramChange(4)   // 0
  object ElectricPiano2     extends ProgramChange(5)   // 0
  object Harpsichord        extends ProgramChange(6)   // 0
  object Clavi              extends ProgramChange(7)   // 0
  object Celesta            extends ProgramChange(8)   // 0
  object Glockenspiel       extends ProgramChange(9)   // 0
  object MusicBox           extends ProgramChange(10)  // 0
  object Vibraphone         extends ProgramChange(11)  // 0
  object Marimba            extends ProgramChange(12)  // 0
  object Xylophone          extends ProgramChange(13)  // 0
  object TubularBells       extends ProgramChange(14)  // 0
  object Dulcimer           extends ProgramChange(15)  // 0
  object DrawbarOrgan       extends ProgramChange(16)  // 0
  object PercussiveOrgan    extends ProgramChange(17)  // 0
  object RockOrgan          extends ProgramChange(18)  // 0
  object ChurchOrgan        extends ProgramChange(19)  // 0
  object ReedOrgan          extends ProgramChange(20)  // 0
  object Accordion          extends ProgramChange(21)  // 0
  object Harmonica          extends ProgramChange(22)  // 0
  object TangoAccordion     extends ProgramChange(23)  // 0
  object AcousticGuitarNyl  extends ProgramChange(24)  // 0
  object AcousticGuitarSte  extends ProgramChange(25)  // 0
  object ElectricGuitarJaz  extends ProgramChange(26)  // 0
  object ElectricGuitarCle  extends ProgramChange(27)  // 0
  object ElectricGuitarMut  extends ProgramChange(28)  // 0
  object OverdrivenGuitar   extends ProgramChange(29)  // 0
  object DistortionGuitar   extends ProgramChange(30)  // 0
  object GuitarHarmonics    extends ProgramChange(31)  // 0
  object AcousticBass       extends ProgramChange(32)  // 0
  object ElectricBassFinge  extends ProgramChange(33)  // 0
  object ElectricBassPick   extends ProgramChange(34)  // 0
  object FretlessBass       extends ProgramChange(35)  // 0
  object SlapBass1          extends ProgramChange(36)  // 0
  object SlapBass2          extends ProgramChange(37)  // 0
  object SynthBass1         extends ProgramChange(38)  // 0
  object SynthBass2         extends ProgramChange(39)  // 0
  object Violin             extends ProgramChange(40)  // 0
  object Viola              extends ProgramChange(41)  // 0
  object Cello              extends ProgramChange(42)  // 0
  object Contrabass         extends ProgramChange(43)  // 0
  object TremoloStrings     extends ProgramChange(44)  // 0
  object PizzicatoStrings   extends ProgramChange(45)  // 0
  object OrchestralHarp     extends ProgramChange(46)  // 0
  object Timpani            extends ProgramChange(47)  // 0
  object StringEnsemble1    extends ProgramChange(48)  // 0
  object StringEnsemble2    extends ProgramChange(49)  // 0
  object SynthStrings1      extends ProgramChange(50)  // 0
  object SynthStrings2      extends ProgramChange(51)  // 0
  object ChoirAahs          extends ProgramChange(52)  // 0
  object VoiceOohs          extends ProgramChange(53)  // 0
  object SynthVoice         extends ProgramChange(54)  // 0
  object OrchestraHit       extends ProgramChange(55)  // 0
  object Trumpet            extends ProgramChange(56)  // 0
  object Trombone           extends ProgramChange(57)  // 0
  object Tuba               extends ProgramChange(58)  // 0
  object MutedTrumpet       extends ProgramChange(59)  // 0
  object FrenchHorn         extends ProgramChange(60)  // 0
  object BrassSection       extends ProgramChange(61)  // 0
  object SynthBrass1        extends ProgramChange(62)  // 0
  object SynthBrass2        extends ProgramChange(63)  // 0
  object SopranoSax         extends ProgramChange(64)  // 0
  object AltoSax            extends ProgramChange(65)  // 0
  object TenorSax           extends ProgramChange(66)  // 0
  object BaritoneSax        extends ProgramChange(67)  // 0
  object Oboe               extends ProgramChange(68)  // 0
  object EnglishHorn        extends ProgramChange(69)  // 0
  object Bassoon            extends ProgramChange(70)  // 0
  object Clarinet           extends ProgramChange(71)  // 0
  object Piccolo            extends ProgramChange(72)  // 0
  object Flute              extends ProgramChange(73)  // 0
  object Recorder           extends ProgramChange(74)  // 0
  object PanFlute           extends ProgramChange(75)  // 0
  object BlownBottle        extends ProgramChange(76)  // 0
  object Shakuhachi         extends ProgramChange(77)  // 0
  object Whistle            extends ProgramChange(78)  // 0
  object Ocarina            extends ProgramChange(79)  // 0
  object Lead1Square        extends ProgramChange(80)  // 0
  object Lead2Sawtooth      extends ProgramChange(81)  // 0
  object Lead3Calliope      extends ProgramChange(82)  // 0
  object Lead4Chiff         extends ProgramChange(83)  // 0
  object Lead5Charang       extends ProgramChange(84)  // 0
  object Lead6Voice         extends ProgramChange(85)  // 0
  object Lead7Fifths        extends ProgramChange(86)  // 0
  object Lead8BassLead      extends ProgramChange(87)  // 0
  object Pad1NewAge         extends ProgramChange(88)  // 0
  object Pad2Warm           extends ProgramChange(89)  // 0
  object Pad3Polysynth      extends ProgramChange(90)  // 0
  object Pad4Choir          extends ProgramChange(91)  // 0
  object Pad5Bowed          extends ProgramChange(92)  // 0
  object Pad6Metallic       extends ProgramChange(93)  // 0
  object Pad7Halo           extends ProgramChange(94)  // 0
  object Pad8Sweep          extends ProgramChange(95)  // 0
  object FX1Rain            extends ProgramChange(96)  // 0
  object FX2Soundtrack      extends ProgramChange(97)  // 0
  object FX3Crystal         extends ProgramChange(98)  // 0
  object FX4Atmosphere      extends ProgramChange(99)  // 0
  object FX5Brightness      extends ProgramChange(100) // 0
  object FX6Goblins         extends ProgramChange(101) // 0
  object FX7Echoes          extends ProgramChange(102) // 0
  object FX8SciFi           extends ProgramChange(103) // 0
  object Sitar              extends ProgramChange(104) // 0
  object Banjo              extends ProgramChange(105) // 0
  object Shamisen           extends ProgramChange(106) // 0
  object Koto               extends ProgramChange(107) // 0
  object Kalimba            extends ProgramChange(108) // 0
  object BagPipe            extends ProgramChange(109) // 0
  object Fiddle             extends ProgramChange(110) // 0
  object Shanai             extends ProgramChange(111) // 0
  object TinkleBell         extends ProgramChange(112) // 0
  object Agogo              extends ProgramChange(113) // 0
  object SteelDrums         extends ProgramChange(114) // 0
  object Woodblock          extends ProgramChange(115) // 0
  object TaikoDrum          extends ProgramChange(116) // 0
  object MelodicTom         extends ProgramChange(117) // 0
  object SynthDrum          extends ProgramChange(118) // 0
  object ReverseCymbal      extends ProgramChange(119) // 0
  object GuitarFretNoise    extends ProgramChange(120) // 0
  object BreathNoise        extends ProgramChange(121) // 0
  object Seashore           extends ProgramChange(122) // 0
  object BirdTweet          extends ProgramChange(123) // 0
  object TelephoneRing      extends ProgramChange(124) // 0
  object Helicopter         extends ProgramChange(125) // 0
  object Applause           extends ProgramChange(126) // 0
  object Gunshot            extends ProgramChange(127) // 0
  object StandardKit        extends ProgramChange(0)   // 0

}
